# Generated by Django 5.2.2 on 2025-06-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField()),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Perfil de LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Perfil de GitHub')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos Personales',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('descripcion_corta', models.CharField(blank=True, help_text='Descripción breve para mostrar en la vista principal', max_length=200, null=True, verbose_name='Descripción corta')),
                ('link_github', models.URLField(blank=True, null=True, verbose_name='Enlace a GitHub')),
                ('link_demo', models.URLField(blank=True, null=True, verbose_name='Enlace a demostración')),
                ('tecnologias', models.CharField(blank=True, help_text='Separar con comas (ej: Python, Django, PostgreSQL)', max_length=300, null=True, verbose_name='Tecnologías principales')),
                ('frontend', models.CharField(blank=True, help_text='Separar con comas (ej: React, Vue.js, HTML, CSS)', max_length=200, null=True, verbose_name='Tecnologías Frontend')),
                ('backend', models.CharField(blank=True, help_text='Separar con comas (ej: Django, Node.js, Express)', max_length=200, null=True, verbose_name='Tecnologías Backend')),
                ('base_datos', models.CharField(blank=True, help_text='Separar con comas (ej: PostgreSQL, MongoDB, Redis)', max_length=200, null=True, verbose_name='Base de datos')),
                ('otras_librerias', models.CharField(blank=True, help_text='Separar con comas (ej: TensorFlow, Pandas, JWT)', max_length=200, null=True, verbose_name='Otras librerías')),
                ('estado', models.CharField(choices=[('desarrollo', 'En Desarrollo'), ('completado', 'Completado'), ('pausado', 'Pausado'), ('mantenimiento', 'En Mantenimiento')], default='desarrollo', max_length=20, verbose_name='Estado del proyecto')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('destacado', models.BooleanField(default=False, verbose_name='Proyecto destacado')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-destacado', 'orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título de la imagen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='curriculum.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de Proyecto',
                'verbose_name_plural': 'Imágenes de Proyectos',
                'ordering': ['orden', 'created_at'],
            },
        ),
    ]
