# Generated by Django 5.2.2 on 2025-06-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción profesional'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
    ]
