# Generated by Django 5.2.2 on 2025-06-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_datospersonales'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='backend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='base_datos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='frontend',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='otras_librerias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
